name: Deploying An Android App

on: pull_request



jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      - name: Run Tests
        run: ./gradlew test

      - name: Build Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Artifact To Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: internal
          file: app/build/outputs/apk/debug/app-debug.apk
