name: Deploying An Android App

on: pull_request

jobs:
  build:
    name: Building The App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11


  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Unit tests
        run: ./gradlew assembleDebug


  deploy:
    name: Upload apk to App Tester
    runs-on: ubuntu-latest

    steps:
      - name: Build Release
        run: ./gradlew assembleDebug
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: '1:1075187720587:android:1979e96d38ef5c8fe40f8e'
          token: '1//03Nfk__i4uumWCgYIARAAGAMSNwF-L9IrhOfRBJjT3V3r4ns-lQ9geS7geEYwez8F0p_g-gj8dF6a0uiuDNLpUGk8nYGsfVfn2_g'
          groups: internal
          file: app/build/outputs/apk/debug/app-debug.apk

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk




